### ISSUE TITLE
Dead URL in package header for laser_scan_matcher

### ISSUE THREAD

**Issue by slivingston** [ccny-ros-pkg/scan_tools#15]
This concerns `package.xml` in the `laser_scan_matcher` package.
The URL to Andrea Censi's CSM site should be http://censi.mit.edu/software/csm/

**Comment by slivingston** [comment]
Alternatively, it may be more reliable to use http://purl.org/censi/2007/csm

**Comment by 130s** [comment]
Addressed in https://github.com/ccny-ros-pkg/scan_tools/commit/6fab4b68d0035e8ba2034c45b628905308da1625#diff-38d5bb5069c3fe5bdada83f60c91ec98
