### ISSUE TITLE
csm_all.h file not found

### ISSUE THREAD

**Issue by chaiein** [ccny-ros-pkg/scan_tools#18]
There is a continous missing of files starting from csm_all.h. After downloading the csm_all.h file next error of missing another gsl related or csm related file...More than 30 files are missing I downloaded and added but there is no use. I got Debug.h file missing after json-c/json.h file is added as it was missing.

**Comment by 130s** [comment]
Starting from laser_scan_matcher ver 0.3.0, CSM doesn't get built upon compilation and instead it has become an external library and LSM just depends on it. Please consider using DEB version by `apt-get install ros-indigo-scan-tools` that automatically installs dependencies like CSM, if you're on Ubuntu.
