### ISSUE TITLE
plan for releasing deb package

### ISSUE THREAD

**Issue by k-okada** [ccny-ros-pkg/scan_tools#23]
Hi,

I would these packages are super useful, do you have any plan to release these package as deb files? so we can use them just install via apt-get

**Comment by 130s** [comment]
+1 for Indigio where it builds w/o any issues for me.

**Comment by 130s** [comment]
@idryanov @miguelsdc if you all are busy I can help to make a new release into newer ROS distros (maybe Indigo, Jade. Hydro is end-of-life).

**Comment by slivingston** [comment]
I also can help. Has anyone had contact with the repo owners?

**Comment by ubuntuslave** [comment]
Try contacting the author, ivan.dryanovski@gmail.com

Good luck!

**Comment by 130s** [comment]
According to [MaintenanceGuide](http://wiki.ros.org/MaintenanceGuide#Claiming_Maintainership) at ros.org, contacting via issue should be enough (I'm afraid we should better refrain from citing someone's personal email publicly..). Next we may ask for help at ros-release.

**Comment by ubuntuslave** [comment]
Oops. Sorry, I thought his email was publicly available on the repos (for instance in CCNY RGB-D tools) any way.

Carlos

On Sep 24, 2015, at 3:08 PM, Isaac I.Y. Saito <notifications@github.com<mailto:notifications@github.com>> wrote:


According to MaintenanceGuide[wiki.ros.org]<https://urldefense.proofpoint.com/v2/url?u=http-3A__wiki.ros.org_MaintenanceGuide-23Claiming-5FMaintainership&d=BQMCaQ&c=8v77JlHZOYsReeOxyYXDU39VUUzHxyfBUh7fw_ZfBDA&r=SS9AWU1Mt1KiHTnPMcbqmURZQiZkYXUyk3pgYP-mWFs&m=HUAg5k4Pr87xtolG1L3Pzr0tqaPJ5hTN1m7yDSZDi4M&s=TGuf_-KWEwTg2rscG1ovm1JXgotNEWug0kTpLoYET00&e=> at ros.org<http://ros.org>, contacting via issue should be enough (I'm afraid we should better refrain from citing someone's personal email publicly..). Next we may ask for help at ros-release.

**Comment by 130s** [comment]
[Asked a guidance](http://lists.ros.org/pipermail/ros-release/2015-October/004695.html) at ros-release on what to do to move forward.

**Comment by ubuntuslave** [comment]
I'm willing to help, but I have no more Linux computers with the latest Ubuntu nor ROS on them. I really stopped using ROS a couple of years ago because I was tired of dual booting or using virtual machines. 

@130s Let's talk privately to set up the distro and get it working with the latest ROS versions and as debian package. I think @idryanov is busy now working with the Tango project at Google, so please forgive us for taking too long to respond. Contact me a ubuntuslave AT Ge MALE . Kom

**Comment by 130s** [comment]
@ubuntuslave Progress made by @wjwwood at [ML](http://lists.ros.org/pipermail/ros-release/2015-October/004698.html) and seems like you have a write access. Could you move forward make a new release?

**Comment by ubuntuslave** [comment]
I added @130s and @wjwwood as collaborators to the scan_tools repo. Let me know how else I can help.

**Comment by wjwwood** [comment]
I don't actually have time to administrate the repository, but I'm glad to help on specific tasks when asked to.

**Comment by ubuntuslave** [comment]
Can @130s help us by making "a new release into newer ROS distros "?

**Comment by 130s** [comment]
@ubuntuslave Sure. I'm waiting for https://github.com/ccny-ros-pkg/scan_tools/issues/26 to move forward.

**Comment by 130s** [comment]
Done for Indigo https://github.com/ros/rosdistro/pull/9652

**Comment by k-okada** [comment]
Thanks you!!! :smile:
