### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by 130s** [ccny-ros-pkg/scan_tools#38]
To avoid confusion like https://github.com/ccny-ros-pkg/scan_tools/pull/37

(I can't execute it since I don't have admin access for this repository.)

**Comment by ubuntuslave** [comment]
Should it be just deleted? Let me know, so I do it in your behalf.

**Comment by 130s** [comment]
> Should it be just deleted?

Yes that was my suggestion.

**Comment by ccny-ros-pkg** [comment]
Done!
