### ISSUE TITLE
Laser Scan Matcher: Option to publish pose with covariance (stamped)

### ISSUE THREAD

**Issue by tappan-at-git** [ccny-ros-pkg/scan_tools#43]
Many localization packages require poses with covariance instead of raw poses (e.g. Robot Localization). Additionally, laser_scan_matcher does not use CSM's computed covariances even when the do_compute_covariance parameter is set.

**Comment by 130s** [comment]
Addressed via #44

**Comment by ubuntuslave** [comment]
Thank you guys!
