### ISSUE TITLE
laser_scan_matcher license

### ISSUE THREAD

**Issue by Minipada** [ccny-ros-pkg/scan_tools#49]
Hello,

I was checking the license and there are 2 listed in the [package.xml](https://github.com/ccny-ros-pkg/scan_tools/blob/indigo/laser_scan_matcher/package.xml#L18). Which one is it?

Thanks!

**Comment by 130s** [comment]
Good question, I don't know the answer to that, and quick research didn't return specific answers either ([this page](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Multiple_Licensing_Scenarios) was helpful but I'm still not clear what to do). If you could figure that out and let us know, that'll be appreciated.

A little background of the situation:
- `scan_tools` ROS package itself was written under `BSD`.
- [csm](http://wiki.ros.org/csm), which a part of scan_tools depends on, is `LGPL`.

**Comment by 130s** [comment]
Dup of https://github.com/CCNYRoboticsLab/scan_tools/issues/76
