### ISSUE TITLE
laser_scan_matcher.cpp

### ISSUE THREAD

**Issue by 772894624** [ccny-ros-pkg/scan_tools#66]
hi，I do not understand why got  the "
// account for the change since the last kf, in the fixed frame
pr_ch = pr_ch * (f2b_ * f2b_kf_.inverse());
 // the predicted change of the laser's position, in the laser frame
 tf::Transform pr_ch_l;
 pr_ch_l = laser_to_base_ * f2b_.inverse() * pr_ch * f2b_ * base_to_laser_ ;" in the laser_scan_matcher.cpp. 
Can someone explain it to me？
thanks！

**Comment by 130s** [comment]
Closing as https://github.com/CCNYRoboticsLab/scan_tools/pull/79 seems to be meant to address the question. If it doesn't, please feel free to add more info.
