### ISSUE TITLE
Release for Melodic and Noetic

### ISSUE THREAD

**Issue by simonbogh** [ccny-ros-pkg/scan_tools#67]
Hi,

Are there any plans to update and release the package so it becomes available for Melodic and Noetic?

**Comment by stwirth** [comment]
ping @130s

**Comment by 130s** [comment]
Ok...I'm no longer a user but have just started updating CI for M and N. https://github.com/ccny-ros-pkg/scan_tools/pull/68

**Comment by 130s** [comment]
- M: https://github.com/ros/rosdistro/pull/28331
- N: https://github.com/ros/rosdistro/pull/28332

Release will be completed when:
- Done for those who use from source, or on non-Ubuntu platform.
- For Ubuntu users who wish to use binary installer, once they are merged AND OSRF announces their apt repo is in sync.

Either way, I'm closing this as we're very close. Please feel free to leave comments for questions.

**Comment by stwirth** [comment]
Thank you @130s!
