### ISSUE TITLE
Laser scan matcher demo 

### ISSUE THREAD

**Issue by rachelzh9** [ccny-ros-pkg/scan_tools#73]
I'm using ROS noetic on Ubuntu 20.04. After trying installing from binary and source, I tried running the demo. However, the laser scans don't seem to appear on rviz even though data is being published on the /scan topic. Maybe it has to do with these warnings?
[ WARN] [1643756842.717890740, 1282836372.062793756]: Invalid argument "/laser" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: 
[ WARN] [1643756842.726900821, 1282836372.073038758]: Could not get initial transform from base to laser frame, Lookup would require extrapolation 0.080653429s into the past.  Requested time 1282836371.072047472 but the earliest data is at time 1282836371.152700901, when looking up transform from frame [laser] to frame [base_link]
[ WARN] [1643756842.727017528, 1282836372.073038758]: Skipping scan

Any help on this would be great! Thanks.

**Comment by 130s** [comment]
Supposed to be addressed by https://github.com/CCNYRoboticsLab/scan_tools/pull/77
